# Configuration for the prometheus-operator chart.
# Reference: https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml
#
# WARNING: the prometheus-operator chart is complicated and error-prone. If you
# edit this file, run the following command to generate the output with `helm
# template`, and verify that your changes have the expected effect.
#
#   bazel build src/app_charts/prometheus/prometheus-operator-chart.robot.yaml

global:
  rbac:
    create: false
    pspEnabled: false

nameOverride: kube
fullnameOverride: kube

alertmanager:
  enabled: false

prometheusOperator:
  # Recent Kubernetes version provide a kube-system/kubelet service by default.
  kubeletService:
    enabled: false
  tlsProxy:
    enabled: false

prometheus:
  prometheusSpec:
    # Pick up all service monitors across all namespaces.
    serviceMonitorNamespaceSelector:
      any: true
    serviceMonitorSelector:
      any: true
    ruleNamespaceSelector:
      any: true
    retention: "3d"

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
coreDns:
  enabled: false
kubelet:
  enabled: false

# Throws an invalid namespace "kube-system" error during deployment
kubeProxy:
  enabled: false

# Subcharts

kube-state-metrics:
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false

prometheus-node-exporter:
  rbac:
    create: false
  podSecurityPolicy:
    enabled: false
  extraArgs:
    # This is disabled by default, since it might leak memory
    # (https://github.com/prometheus/node_exporter/blob/master/CHANGELOG.md#0160-rc1--2018-04-04)
    - --collector.wifi

grafana:
  enabled: false
