apiVersion: apps/v1
kind: Deployment
metadata:
  name: cr-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-syncer
  template:
    metadata:
      labels:
        app: cr-syncer
    spec:
      containers:
      - name: cr-syncer
        args:
        - -remote-server
        - {{ .Values.domain }}
        - --robot-name
        - "{{ .Values.robot.name }}"
        - -alsologtostderr
        - --verbose=false
        - --listen-address=:80
        image: {{ .Values.registry }}{{ .Values.images.cr_syncer }}
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cr-syncer
  labels:
    app: cr-syncer
spec:
  selector:
    app: cr-syncer
  ports:
  - name: http
    port: 80
    targetPort: http
