{{ if eq .Values.robot_authentication "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gcr-credential-refresher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcr-credential-refresher
    spec:
      containers:
      - image: {{ .Values.registry }}{{ .Values.images.gcr_credential_refresher }}
        name: gcr-credential-refresher
        resources:
          requests:
            cpu: "1m"
            memory: "50Mi"
          limits:
            cpu: "10m"
            memory: "200Mi"
{{ end }}
