{{ if eq .Values.app_management "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robot-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: robot-master
    spec:
      containers:
      - args:
        - "--namespace={{ .Release.Namespace }}"
        - "--labels=app=robot-master"
        - "--webhook-port=9876"
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: {{ .Values.project }}
        - name: ROBOT_NAME
          value: "{{ .Values.robot.name }}"
        image: {{ .Values.images.robot_master }}
        name: robot-master
        volumeMounts:
        - mountPath: /home
          name: home
      initContainers:
      # Run `helm init` to create client-side directories in $HOME/.helm which
      # some client library functionality expects to exist.
      - name: helm
        image: {{ .Values.images.robot_master }}
        command: ['/helm', 'init', '--client-only']
        volumeMounts:
        - mountPath: /home
          name: home
      volumes:
      - name: home
        emptyDir: {}
{{ end }}
