# This defines a service in the robot cluster, available at:
#   ros-master-<robot name>.app-ros-master.svc.cluster.local
# The user can configure what it points to by setting `values.ros_master_host`
# in the AppRollout, allowing a single-point-of-configuration for the ROS
# master. Note that this can't specify the port, so deployments should set:
#   ROS_MASTER_URI=http://ros-master.app-ros-master.svc.cluster.local:11311
apiVersion: v1
kind: Service
metadata:
  name: ros-master
spec:
  type: ExternalName
  externalName: {{ tpl (required "missing required value ros_master_host" .Values.ros_master_host) . }}
