# This defines a service in the robot cluster, available at:
#   ros-master-<robot name>.app-ros-master.svc.cluster.local
# The user can configure what it points to by setting `values.ros_master_host`
# in the AppRollout, allowing a single-point-of-configuration for the ROS
# master. Note that this can't specify the port, so deployments should set:
#   ROS_MASTER_URI=http://ros-master.app-ros-master.svc.cluster.local:11311
{{ $ipv4Pattern := `(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}` }}
{{ $host := tpl (required "missing required value ros_master_host" .Values.ros_master_host) . }}
{{ if regexMatch $ipv4Pattern $host }}
# Host is an IPv4 address, so use a headless Service.
apiVersion: v1
kind: Service
metadata:
  name: ros-master
spec:
  type: ClusterIP
  ports:
  - name: ros-master-api
    port: 11311
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ros-master
subsets:
- addresses:
  - ip: {{ $host }}
  ports:
  - name: ros-master-api
    port: 11311
{{ else }}
# Host is a DNS name, so use an ExternalName Service.
apiVersion: v1
kind: Service
metadata:
  name: ros-master
spec:
  type: ExternalName
  externalName: {{ $host }}
{{ end }}
