# This includes all resources expanded from the prometheus-operator chart using
# the values in ../prometheus-cloud.values.yaml.
# Some pseudo-variables that were inserted there are replaced with actual runtime values.
# TODO(rodrigoq): This severely limits how the end-user can customize the
# prometheus deployment. How could we let them override prometheus-cloud.values.yaml?
{{ .Files.Get "files/prometheus-operator-chart.cloud.yaml" | replace "${CLOUD_ROBOTICS_DOMAIN}" .Values.domain | replace "${GCP_PROJECT_ID}" .Values.project | replace "HELM-NAMESPACE" .Release.Namespace | replace "${MEMORY_REQUEST}" .Values.memory_request | replace "${CPU_REQUEST}" .Values.cpu_request }}
