domain: "example.com"
project: "my-gcp-project"
project_number: 0
deploy_environment: "GCP"
registry: "gcr.io/my-gcp-project"

# Setting app_management to "false" will remove layer 2 (robot/cloud-master, etc).
app_management: "true"
use_synk: "false"

# Setting robot_authentication to "false" will remove layer 1 resources that are not
# needed when simulating a robot with a GKE cluster, such as the
# metadata-server or gcr-credential-refresher.
robot_authentication: "true"

robot:
  name: ""

webhook:
  enabled: "true"
  tls:
    key: ""
    crt: ""
